feat(buf): Switch to Buf for protobuf generation, lint and BSR (#380)
* chore: Switch to Buf for protobuf generation

* ci: Remove Protoc install steps from CI workflow

* feat: Integrate Buf for Protobuf linting and dependency locking

* chore: Update Buf config and lint workflow

* feat: Add GitHub Action to push module to BSR

* feat: Add GitHub Actions workflow to publish modules to BSR

* chore: add comments

* chore: improve README

---------

Co-authored-by: wenchy <wenchy.zwz@gmail.com>

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -24,3 +24,22 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           version: v2.2.1
+
+      - name: Install Buf
+        uses: bufbuild/buf-action@v1
+        with:
+          version: 1.67.0
+          setup_only: true
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Buf Lint
+        run: buf lint
+
+      - name: Buf Generate and Check
+        run: |
+          buf generate
+          if git diff --name-only | grep -q "\.go$"; then
+            echo "Error: Generated Go files are not committed"
+            git diff
+            exit 1
+          fi
